### ISSUE TITLE
Cannot install nodes

### ISSUE THREAD

**Issue by Ansciad** [OpenChrom/knimeconnector#5]
Hi,
So excited if I could analyse LC/GC datas on knime, thanks for your work. But... I cannot complete the install because no item can be found on https://update.openchrom.net/repositories/knime/3.5.0. I'm working on knime 4.0 for MacOs. 
Any idea?
Thanks

**Comment by kerner1000** [comment]
Hi, many thanks for your feedback! I am working on this issue right now. Should be resolved soon.

**Comment by kerner1000** [comment]
Resolved with e548b008c9f834c24dbad95fd850c148a77ef01e and 12fd15dfe455e793b81b4e59b5011d953b709f1a.

**Comment by Ansciad** [comment]
Thanks for your effectiveness! However, I only could install NMR nodes, but not other nodes (CSD, MSD or visualization). Something wrong from my part?

**Comment by kerner1000** [comment]
Currently, there are only NMR nodes available. Can you specify which file you want to process using a KNIME node? I would try to find a solution for this case.

**Comment by Ansciad** [comment]
Ok, my bad, I thought LC nodes were available. I wanted to process a LC chromatogram (csv file for the moment) to do stuff like peak piking, half height width or area calculations.

**Comment by kerner1000** [comment]
If the chromatogram is stored as CSV, then you can use a KNIME-internal reader. If there are Peak Picking algorithms available, I dont know. OpenChrom algorithms currently do not work on "text-based"-data models, a conversion would be necessary here.

**Comment by Ansciad** [comment]
Well, it's even better if OpenChrom algorithms work on proprietary files. But still, how do you get CSD and MSD nodes from your repository? (As seen in the screen shot). Thanks by advance
![Capture d’écran 2019-10-16 à 16 28 25](https://user-images.githubusercontent.com/56563769/66959253-3e10d180-f06a-11e9-9e1e-22dd89e5d245.png)
